{% set data = load_setup_py_data(setup_file='../../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.get('name') }}
  version: {{ data.get('version') }}

build:
  number: 1
  script_env:
   - WHEEL

 

requirements:
  build:
    - python {{ environ.get('PYVERSION', '') }}
    - pip
    - numpy
    - cython
    - mkl 
    - mkl-include
  run:
    - python {{ environ.get('PYVERSION', '') }}
    - numpy
    - scipy
    - numexpr
    - mkl
    - h5py
    - numba



about:
  home: http://github.com/fzimmermann89/idi
  license: BSD 2-Clause
  summary: IDI
