[project]
requires-python = ">=3.6"

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "oldest-supported-numpy", "Cython", "mkl==2019; sys_platform == 'darwin'", "mkl; sys_platform == 'linux'", "mkl-include==2019; sys_platform != 'win32'", "mkl-devel; sys_platform == 'win32'"]

[tool]