name: Singularity
on:
  - push
jobs:
  build_singularity:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Singularity install with defaults
        uses: singularityhub/install-singularity@main
      - run: df -h .
      - name: Free disk space
        run: sudo rm -rf /usr/share/dotnet /usr/share/swift /opt/ghc/
          /opt/hostedtoolcache/Ruby /opt/hostedtoolcache/node
          /opt/hostedtoolcache/CodeQL /usr/local/lib/android
      - run: df -h .
      - name: build image
        run: sudo singularity build image.sif Singularity
      - name: upload image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo ${{ secrets.SYLABS_TOKEN }} > sylabs-token
          singularity remote login --tokenfile sylabs-token
          singularity push -U image.sif library://fzimmermann89/idi/idi