name: Singularity

on: [push]

jobs:
  build_singularity:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: '1.15'
    - run: |
        sudo apt install -y build-essential libssl-dev  uuid-dev libgpgme11-dev squashfs-tools libseccomp-dev pkg-config 
        sudo chmod u+x .github/*.sh && /bin/bash .github/setupsingularity.sh
    
    - run: df -h . 
    - name: Free disk space
      run: sudo rm -rf /usr/share/dotnet /usr/share/swift /opt/ghc/ /opt/hostedtoolcache/Ruby /opt/hostedtoolcache/node /opt/hostedtoolcache/CodeQL /usr/local/lib/android
    - run: df -h . 

    - name: build image
      run: sudo singularity build image.sif Singularity
      
    - name: upload image
      run: |
         echo ${{ secrets.SYLABS_TOKEN }} > sylabs-token
         singularity remote login --tokenfile sylabs-token
         singularity push -U image.sif library://fzimmermann89/idi/idi
      

