name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-flake8
        pip install .
    - name: Syntax check
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Test
      run: |
        pytest --flake8 --ignore=scripts --ignore=ipynb --ignore=kossel
